### ISSUE TITLE
Crashing when doing Segmentation very often 

### ISSUE THREAD

**Issue by hwjung92** [MITK/MITK#286]
MITK tool is really useful to display the dicom images and labelled images rapidly.
There is a critical issue when using the segmentation tool.
The button of Add and Subtract tool in the segmentation is working well at the first time.
However, MITK APP crashed suddenly when doing segmentation very often.
That issue makes me change the main tool to 3D Slicer. 
Please update this error.

**Comment by kislinsk** [comment]
Hi, thank you for the report. Since we cannot reproduce your issue in general we would like to ask you for more details.

Which version of MITK are you using?

Which OS and version are you using?

What is the output in the console/terminal when the crash is happening?

Do you use other tools than Add/Subtract (btw, did you know you can inverse the behavior of these tools while pressing CTRL? No need to switch between the tools.)?

Do you use interpolation in segmentation? If yes, which one, 2-d or 3-d?

Do you use Segmentation Utilities?

Do you create multiple labels or label groups?

Do you delete labels or label groups?

Do you use undo/redo?

Can you remember exactly at which action the crash happened?

Anything to narrow down the issue helps.
