### ISSUE TITLE
DICOM QUERY RETRIVAL ISSUE (ERROR LOGS)

### ISSUE THREAD

**Issue by amitjc** [MITK/MITK#293]
Dear Experts,

We are loving the MITK appllication for its post processing capabilities. 

We tried setting up DICOM query retrieval on MITK Workbench v2024.06.2, however retrieval fails, with following error message.
 
```
I: Releasing Association
#63.325# ERROR: Setting Transfer Syntaxes
I: Requesting Association
I: Association Accepted (Max Send PDV: 28660)
I: Sending C-FIND Request (MsgID 1)
I: Received C-FIND Response (Pending)
I: Received C-FIND Response (Success)
I: Sending C-FIND Request (MsgID 2)
I: Received C-FIND Response (Pending)
I: Received C-FIND Response (Success)
I: Releasing Association
#63.986# ERROR: setting value to 0
I: Requesting Association
I: Association Accepted (Max Send PDV: 28660)
I: Sending C-MOVE Request (MsgID 1)
I: Received C-MOVE Response (Refused: MoveDestinationUnknown)
#64.004# ERROR: setting value to 0
E: DIMSE status is: Refused: MoveDestinationUnknown
#64.012# ERROR: MOVE request failed, server does report error
#64.012# ERROR: MOVE request failed: Status Detail:
# Dicom-Data-Set
# Used TransferSyntax: Little Endian Implicit
(0000,0902) LO [DESTINATION_NODE_NOT_FOUND]             #  26, 1 ErrorComment
I: Releasing Association
```

Seek guidance to address the issue.

Thanks and Regards,
Amit,.

**Comment by lassoan** [comment]
> E: DIMSE status is: Refused: MoveDestinationUnknown

This means that the IP address of your computer has not been registered in the PACS known hosts list. You can run queries but you won't be able to retrieve any images until the administrator adds your computer's IP address.

If you work on a laptop that is assigned a dynamic IP address (or several members of the research group wants to get access on their computers) then IT admins may not be able to grant access to you. For these cases, we added the proxy server feature to the new DICOM browser in CTK (3D Slicer already uses that, probably MITK does not support it yet, but it would be not too difficult to integrate it): you set up an Orthanc server on any computer with a static IP (really easy, either an interactive installer or docker), register that computer with IT; in the visual DICOM browser you add both the PACS and the Orthanc server to the DICOM host list and mark the Orthanc server as proxy for the PACS. This allows any computer in the your lab (that you grant access to your Orthanc server) query and retrieve images from anywhere. This all works because Orthanc supports the C-GET protocol, which does not require a static IP but sends the images to the client on the same connection as the query.
