### ISSUE TITLE
MITK and VTK compiling

### ISSUE THREAD

**Issue by CugAgo** [MITK/MITK#294]
If I have already compiled VTK on my computer, will it conflict with my local VTK environment when compiling MITK, and do I need to configure anything in cmake？

**Comment by kislinsk** [comment]
MITK uses a super-build approach. Instead of configuring and building MITK only, the MITK super-build also downloads, configures, and builds (nearly) all of its dependencies. Hence, an MITK build can be considered isolated and does not interfere or conflict with any existing builds of its dependencies.

Exceptions prove the rule, though. The two most prominent counter examples are probably Qt v6.6+ and OpenSSL, which are not included in the MITK super-build but searched for during the configure step.

If you want to use your own build of VTK with MITK, you can do so by setting `EXTERNAL_VTK_DIR` during the configure step. This is considered an advanced feature, though, and we strongly recommend to go with a plain vanilla default standard build first before getting creative with building MITK with more complex configurations.

For more information, see the [Build Instructions](https://docs.mitk.org/2024.06/BuildInstructionsPage.html).
